spring.application.name=prisma_api

api.security.token.secret=${JWT_SECRET:my-secret-key}
# Database Config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/prisma_erp
spring.datasource.username=postgres
spring.datasource.password=@Rrm565756

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true